### ISSUE TITLE
Won't update hosts file to offer alias for public IP of Minikube's VirtualBox VM

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote-selfmedicate#39]
I've tested latest version of selfmedicate.sh.
The message at the end will instruct to connect on http://antidote-local:30001/:
```Finished! Antidote should now be available at http://antidote-local:30001/```

However that machine name doesn't resolve.
Still it works on the public IP of the VirtualBox VM
```
./minikube status
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.133

./kubectl get service/nginx-ingress
NAME            TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
nginx-ingress   NodePort   10.111.217.28   <none>        80:30001/TCP   8m50s
```
So connecting to http://192.168.99.133:30001/ works.

Hope this helps.

P.S. haven't had time to investigate the script yet.
Hence

**Comment by olberger** [comment]
minikube ip seems to be a much better way to find the IP, btw.

Tested with 1.3.1 or 1.4.0 (that latter has issues with lots of gibberish output on the console, btw).

**Comment by olberger** [comment]
I think I found the culprit : https://github.com/nre-learning/antidote-selfmedicate/commit/dcab5e26244d2353b48987f39982b49dd158b33e#r35409091

**Comment by Mierdin** [comment]
So, there's a few things going on here. I might be wrong but it *looks* like you're running minikube directly, and with the virtualbox driver. You're of course, welcome to do this, but the only method we're currently supporting is through the Vagrantfile, which runs with the `none` driver. This also makes `minikube ip` a bit pointless, because in this case it would just show the internal NAT'd address of the vagrant VM.

The vagrantfile also includes steps to modify the hosts file on the host running the Vagrant machine, which points `antidote-local` to the address of the box provisioned by Vagrant.

Finally, this hosts entry is actually super important as the current ingress configuration for Syringe as well as any `http` presentations provisioned by Syringe rely on that to get the application routing right - so while using the IP to connect will successfully get to the web UI (since it's the default route in the ingress), it won't work for anything else. Gotta use `antidote-local`.

I'm going to close this, since it seems like all this should be resolved by following https://antidoteproject.readthedocs.io/en/latest/hacking/curriculum/vagrantfile.html - but I hope the additional detail was useful.

**Comment by olberger** [comment]
Sure, it all makes more sense.
