### ISSUE TITLE
Please document antibridge

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote-selfmedicate#75]
Would you be able to document antibridge ?

Its repo seemed to be forked off CNI... but that ain't really documented AFAICS

https://github.com/nre-learning/antidote-selfmedicate/blob/f02ddf4fd2e3315967421c54ecb059b68069baa2/selfmedicate.sh#L111

Also, would it be contributable to the original project (not maintaining a forked version, etc.) ?

Thanks in advance.

**Comment by Mierdin** [comment]
As discussed, this is really no different than the bridge plugin, other than setting a single flag to permit LLDP. We never got where we wanted to with the rest of LLDP support, so this is pointless. Rather than documenting this, I'd like to remove it. I'll open an issue in antidote-core to remove references to this and once antidote-core supports the regular bridge plugin again we can remove this from selfmedicate.
